### PR TITLE
update avatar with gravatar

### LINKED ISSUE #19: Players should automatically default their avatar within Rocket.Chat to their gravatar
(requires Mongo file upload)

### PR DESCRIPTION
**Pull request by jeffreywescott**
Fixes #19.

Always update the echo avatar to match the gravatar associated with the primary Learners Guild IDM email.

### CODE REVIEW

**Comment by heyheyjp** [comment]
So does this mean that they'll never be able to get changes made to their avatar directly in echo chat to stick? If so, should we be concerned about any confusion if they _do_ attempt to change it (say they upload an image) but find on login every time that it reverts to their gravatar? Wondering if it should only default to the gravatar if there isn't another image set...

**Comment by jeffreywescott** [comment]
Yeah, that's what it means. Actually, if possible, I'd prefer to just eliminate the ability for them to change their avatar in `echo` _at all_, because that won't propagate the change to the rest of our services. I want to enforce handle and avatar consistency across all services.

**Comment by heyheyjp** [comment]
Cool, I like that idea.  👍

**Comment by heyheyjp** [comment]
This LGTM. 👍 

Would like to see that the options for changing avatars any other way (except in ways that will cause the change to be propagated across all services) will be disabled/hidden/whatever to minimize risk of confusing users.

**Comment by jeffreywescott** [comment]
Tracked here:  https://github.com/LearnersGuild/echo-chat/issues/8

**Pull request merged**
